# Generated by Django 2.2 on 2019-04-11 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateRecord',
            fields=[
                ('user_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('rating', models.FloatField(db_index=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
