# Generated by Django 2.2 on 2019-04-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_leaderboard_mv'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('rate_place', models.IntegerField(db_column='rate_place', primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(verbose_name='user_id')),
                ('rating', models.FloatField(db_column='rating')),
                ('datetime', models.DateTimeField(db_column='datetime')),
            ],
            options={
                'db_table': 'leaderboard',
                'managed': False,
            },
        ),
    ]
